server:
  image: postgrest/postgrest
  ports:
    - "3000:3000"
  links:
    - db:db
  environment:
    PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
    PGRST_DB_SCHEMA: api
    PGRST_DB_ANON_ROLE: todo_user

db:
  build: db
  ports:
    - "5435:5432"
  environment:
    POSTGRES_DB: app_db
    POSTGRES_USER: app_user
    POSTGRES_PASSWORD: password
